name: pana
description: A sample command-line application.
version: 0.2.0-dev
homepage: https://github.com/kevmoo/pana.dart
author: Kevin Moore <kevmoo@google.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  logging: ^0.11.3+1
  path: ^1.4.1
  pub_semver: ^1.3.2

dev_dependencies:
  test: ^0.12.0
